[package]
name = "max-data"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["cdylib"]

[profile.release]
lto = true

[dependencies]
pluginop-wasm = { path = "../../pluginop/wasm" }
wasm-bindgen = "0.2"