[package]
name = "privacy-padding"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["cdylib"]

[dependencies]
pluginop-wasm = "0.1"
lazy_static = "1"
wasm-bindgen = "0.2"
fastrand = "2.0.1"

[profile.release]
lto = true