[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["cdylib"]

[profile.release]
lto = true

[dependencies]
pluginop-wasm = "0.1"
lazy_static = "1"
wee_alloc = "0.4.5"
wasm-bindgen = "0.2"