[package]
name = "super-frame"
version = "0.1.0"
edition = "2021"

[lib]
crate-type =["cdylib"]

[dependencies]
pluginop-wasm = "0.1"
lazy_static = "1"
wasm-bindgen = "0.2"

[profile.release]
lto = true